export const MON = 'Mon';
export const TUE = 'Tue';
export const WED = 'Wed';
export const THU = 'Thu';
export const FRI = 'Fri';
export const SAT = 'Sat';
export const SUN = 'Sun';
export const DAILY = 'daily';
export const WEEKLY = 'weekly';
export const MONTHLY = 'monthly';
export const YEARLY = 'yearly';
export const TODAY = 'today';
export const TOMORROW = 'tomorrow';
export const STORAGE_TASK_KEY = new Date().toUTCString();
export const APP_HEADER_COLOR = '#9999ff';
export const APP_BTN_INACTIVE_COLOR = '#b3b3fc';
export const APP_BTN_ACTIVE_COLOR = '#8787ff'